stages:
  - test
  - dev_install
  - install
  - sonar

before_script:
  - pwd
  - echo $CI_BUILD_REF_NAME
  - git remote -v
  - git reset --hard HEAD
  - git stash
  - git pull origin $CI_BUILD_REF_NAME
  - echo $CI_COMMIT_REF_NAME
  - status_one=0
  - status_two=0
  - (ping -w 5 -c 1 192.168.9.61 > /dev/null) || status_one=$? || true
  - if [ $status_one -ne 0 ]; then if [ "$CI_COMMIT_REF_NAME" != "iacs2020/ut" ]; then /opt/vpn.sh start; fi; fi;
  - (ping -w 5 -c 1 192.168.9.60 > /dev/null) || status_two=$? || true
  - if [ $status_two -ne 0 ]; then if [ "$CI_COMMIT_REF_NAME" != "iacs2020/ut" ]; then echo "VPN DOWN" && killall vpnagentd && /opt/vpn.sh stop || exit 1; fi; fi;

after_script:
  - git reset --hard HEAD
  - git stash
  - git pull origin $CI_BUILD_REF_NAME

npm_test:
  stage: test
  script:
    - pwd
    - git reset --hard HEAD
    - rm -rf node_modules
    - npm install
    - npm run test
    - npm run build

mvn_test:
  stage: test
  script:
    - cd backend
    - mvn clean
    - mvn test
    
dev_install:
  stage: install
  script:  
    - pwd
    - cd $CI_PROJECT_DIR/
    - git reset --hard HEAD
    - rm -rf node_modules
    - npm install
    - npm run build-dev
    - cd backend
    - pwd
    - mvn clean install -DskipTests
  except:
    - dev
    - staging
    - master

prod_install:
  stage: install
  script:  
    - pwd
    - cd $CI_PROJECT_DIR/
    - git reset --hard HEAD
    - rm -rf node_modules
    - npm install
    - npm run build
    - cd backend
    - pwd
    - mvn clean deploy -DskipTests
  only:
    - master
    - staging
    - dev

1_perun-core-dev-generate-js:
  stage: dev_install
  script:  
    - pwd
    - cd $CI_PROJECT_DIR/
    - git reset --hard HEAD
    - rm -rf node_modules
    - npm install
    - rm -rf backend/www/*.js
    - npm run build
    - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
    - git remote set-url origin "https://gitlab-ci-token:${K8S_SECRET_GITLABCI_TOKEN}@${url_host}"
    - git remote -v
    - git add backend/www/*.js
    - git commit -m "Auto commit of perun-core library for npm" || exit 0
    - git push origin HEAD:$CI_COMMIT_REF_NAME    
  only:
    - dev
  when: manual


sonarqube_backend:
  stage: sonar
  script:
    - cd $CI_PROJECT_DIR/
    - cd backend
    - mvn sonar:sonar -Dsonar.analysis.mode=preview -Dsonar.projectName=$CI_PROJECT_NAME -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID
  when: manual

sonarqube_backend_publish:
  stage: sonar
  script:
    - cd $CI_PROJECT_DIR/
    - cd backend
    - mvn sonar:sonar -Dsonar.analysis.mode=publish -Dsonar.projectName=$CI_PROJECT_NAME -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Donar.gitlab.user_token access=a18878c7b5beb401ce2f847537c296b46a3902b8 
  environment:
    name: $CI_COMMIT_REF_NAME
  only:
    - staging
    - dev  
  when: manual

sonarqube_frontend:
  stage: sonar
  script:
    - sonar-scanner -Dsonar.sources=. -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.analysis.mode=preview -Dsonar.login=a02003f1f8f90382d7570b57a85c00c38132f85f -Dsonar.branch=$CI_BUILD_REF_NAME -Dsonar.projectName=$CI_PROJECT_NAME -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID
    - sonar-scanner -Dsonar.sources=. -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.analysis.mode=publish -Dsonar.login=a02003f1f8f90382d7570b57a85c00c38132f85f -Dsonar.branch=$CI_BUILD_REF_NAME -Dsonar.projectName=$CI_PROJECT_NAME
  when: manual

