# Project info
projectGroup=${project.groupId}
projectName=${project.artifactId}
version=${project.version}
description=${project.name}

# Frontend access card 
url=spatial.js
icon=spatial.jpg
label=perun.plugin.spatial
permissionCode=card.spatial_access
sortOrder=3